### PR TITLE
compile _queryResult into _result instead of _queryResult

### PR DESCRIPTION
**Pull request by niklashenrixon**
compile _queryResult into _result instead of _queryResult due to the machine thinkin that the result is a variable and reports error

### CODE REVIEW

**Comment by Torndeco** [comment]
I really don't understand what you are trying to fix here...
That code _queryResult call compile _queryResult; 
Is in AltisLifeRPG / A3Wasteland extDB servers etc...
There is no issue with it, unless something got broken by BIS

Am interested in seeing a rpt error for this

**Comment by niklashenrixon** [comment]
Im sorry, I had trouble with this but i know why also. It gave me an error when i was recieving a string from SQL, the problem was solved by putting "OUTPUT 1-STRING" inside the SQL_custom file. However i thought it was solved by doing the solution i pull requested because the first time i ran the code without changing the variable name i was trying to get an array that contained a string without having 1-STRING inside SQL_custom. I (for some reason) changed the variablername BUT also changed my call to only recieve a numeric value. This time i had no error in my rpt.  If you try to recive a string without 1-STRING in your SQL_custom. The rpt log will tell you that the string you're reciving is not a declared variable. This is produced when you are compiling the result to make it a true array. 

So you see, the problem was me changing 2 things in my code and thinking that the variable change was the solution when it really was that i messed up in my SQL_custom call. 

Thanks for an awsome mod btw :)

**Comment by niklashenrixon** [comment]
@Torndeco As I said, awsome mod, but i must say.. the wiki/tutorials are not that self explaining.. could need some improvment. Maybe im not the one to tell you this but thats what i think. Maybe im slow hehe

**Comment by Torndeco** [comment]
Thanks

Everyone is free to edit or improve the wiki's if they can.
It can be abit of work, since some people want examples of storing / retrieving info and have no prior knowledge of SQL / Redis.

Best thing is just try and error and using the wiki as reference material (especially with SQL_CUSTOM).
Also using the Test application makes things abit easier to test out.

**Comment by chris579** [comment]
Yeah, just use the test application, it helps a lot, specifically for searching errors in syntax etc.

**Pull request closed without merging**
