### PR TITLE
Update example.ini

### PR DESCRIPTION
**Pull request by manzarek123**

### CODE REVIEW

**Comment by chris579** [comment]
DB_Custom returned [1,[[]] when the result was empty, DB_Custom_v2 returns [1,[]] when the result is empty. Torndeco corrected this behavior some versions ago.

**Comment by Torndeco** [comment]
Please don't make pull requests for questions....
Its returns the last insert id  i.e   [1,[<INSERT_ID>,[]]]

**Comment by manzarek123** [comment]
Well there was a mistake and i pointed it out.

**Comment by chris579** [comment]
If you find a error fix it instead of putting quadrillions of ? behind it...

**Comment by manzarek123** [comment]
The only place where this command was explained was wrong so there i no easy way for me to find out.
Such drama queens

**Comment by chris579** [comment]
Like Torndeco said: don't make pull requests for questions, they are used to merge code....

**Pull request closed without merging**
